### ISSUE TITLE
"xstate.edit-code-lens not found" when trying to open visual editor

### ISSUE THREAD

**Issue by nstadigs** [statelyai/xstate-vscode#50]
I had an old version installed earlier. I tried to delete the old version and install fresh, but with the same results. It feels like there are things left over from the old version, causing the new version to fail or something.

![image](https://user-images.githubusercontent.com/588215/153002407-b863503c-4ccb-450f-8ac9-bc8c88d911a5.png)

### On plugin activation

```
[2022-02-08 15:22:47.610] [exthost] [error] Error: command 'xstate.visualize' already exists
	at u.registerCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:93:28683)
	at Object.registerCommand (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:107:30423)
	at initiateVisualizer (/home/nbostrm/.vscode/extensions/statelyai.stately-vscode-1.5.16/client/dist/index.js:155145:57)
	at activate (/home/nbostrm/.vscode/extensions/statelyai.stately-vscode-1.5.16/client/dist/index.js:155269:5)
	at async Promise.all (index 0)
	at async w.$activate (/opt/visual-studio-code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:21810)
```

### When trying to run "XState: Open visual editor:

```
[2022-02-08 15:23:20.349] [exthost] [error] Error: command 'xstate.edit-code-lens' not found
    at b._tryExecuteCommand (vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:1489:3364)
    at vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js:1489:3245
    at processTicksAndRejections (internal/process/task_queues.js:93:5) xstate.edit-code-lens undefined
```

![image](https://user-images.githubusercontent.com/588215/153002626-731a028e-ad61-4a43-9b02-2636a748dc6f.png)

## About Visual Studio Code:
```
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:23:11.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.16.4-arch1-1
```

**Comment by nstadigs** [comment]
I figured it out.

I had `mattpocock.xstate-vscode-1.4.1` installed. And since this plugin was removed from the store I could not find it in the "Extensions" panel i vscode. I removed that from the extensions directory in the vscode config directory and restarted vscode. I then reinstalled the extension from stately and now it seems to work :+1:
